# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EventsAppIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '~> 5'	
  pod 'Kingfisher'
  pod 'lottie-ios'

  # Pods for EventsAppIOS

end
