# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'EventsAppIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher', '~> 5.0'
  pod 'lottie-ios'
  pod 'Moya', '~> 14.0'

  # Pods for EventsAppIOS

end
